/* src/configwin32.h.  Generated by configure.  */
/* src/configwin32.h.in.  Generated from configure.in by autoheader.  */


/* Name of package */
#define PACKAGE "seq24"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "seq24-devel@lists.sourceforge.net"

/* Define to the full name of this package. */
#define PACKAGE_NAME "seq24"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "seq24 0.9.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "seq24"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.9.1"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.9.1"

/* gnu source */
#define _GNU_SOURCE 1

/* Define to 1 if you have the `asound' library (-lasound). */
#define HAVE_LIBASOUND 0
#undef HAVE_LIBASOUND

/* Define to enable JACK driver */
#define JACK_SUPPORT 0
#undef JACK_SUPPORT

/* Define to enable LASH support */
#define LASH_SUPPORT 0
#undef LASH_SUPPORT


#define PTHREAD_SUPPORT 1

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

